### ISSUE TITLE
Smart life "belife" smartplug not working

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [rebtor/nl.rebtor.tuya#23]
Perhaps my plug is not supported but i'm not sure. 
![image](https://user-images.githubusercontent.com/1246691/129396852-cbbff27e-6771-41e8-a108-f0874e3de5cb.png)
it says it's temporary unavailable with a dutch error:

> Apparaat Onbeschikbaar
Dit apparaat is tijdelijk onbereikbaar.

via `https://openapi.tuyaeu.com/v1.0/devices?device_ids=....` i'm getting this reponse, is that what your app expects as wel?

```
        "product_id": "jdk24sq7i07oofqo",
        "product_name": "EU02-JX 公版",
        "status": [
          {
            "code": "switch_1",
            "value": true
          },
          {
            "code": "countdown_1",
            "value": 0
          },
          {
            "code": "add_ele",
            "value": 27
          },
          {
            "code": "cur_current",
            "value": 293
          },
          {
            "code": "cur_power",
            "value": 506
          },
          {
            "code": "cur_voltage",
            "value": 2324
          }
        ],
```

**Comment by ricardovanlaarhoven** [comment]
```
─────────────── Logging stdout & stderr ───────────────
[log] 2021-08-17 12:48:11 [Tuyadriver] Tuyadriver is running...
[log] 2021-08-17 12:48:12 [ManagerFlow] [FlowCard] [Soc4_on] Warning: Run listener was already registered.
[log] 2021-08-17 12:48:12 [ManagerFlow] [FlowCard] [Soc4_toff] Warning: Run listener was already registered.
[err] 2021-08-17 12:48:12 [ManagerDrivers] [Driver:NEO_SmartPlug_3600] Error Initing Device Error: Cannot find module 'p-timeout'
Require stack:
- /modules/tuyapi/index.js
- /drivers/NEO_SmartPlug_3600/device.js
- /opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Util.js
- /opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Device.js
- /opt/homey-client/node_modules/homey-apps-sdk-v3/homey.js
- /opt/homey-client/node_modules/homey-apps-sdk-v3/index.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at Module.homeyRequire [as require] (/opt/homey-client/node_modules/homey-apps-sdk-v3/index.js:12:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/modules/tuyapi/index.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/modules/tuyapi/index.js',
    '/drivers/NEO_SmartPlug_3600/device.js',
    '/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Util.js',
    '/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Device.js',
    '/opt/homey-client/node_modules/homey-apps-sdk-v3/homey.js',
    '/opt/homey-client/node_modules/homey-apps-sdk-v3/index.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap.js'
  ]
}

```

**Comment by ricardovanlaarhoven** [comment]
```
"{\"dps\":{\"18\":95,\"19\":25},\"t\":1637409487}\n NEW DATA ATRIBUTE: {\"dps\":{\"18\":75,\"19\":26},\"t\":1637409491}\n NEW DATA ATRIBUTE: {\"dps\":{\"18\":74,\"19\":38},\"t\":1637409493}\n NEW DATA ATRIBUTE: {\"dps\":{\"18\":76,\"19\":32},\"t\":1637409495}\n NEW DATA ATRIBUTE: {\"dps\":{\"18\":75,\"19\":25},\"t\":1637409497}\n NEW DATA ATRIBUTE: {\"dps\":{\"18\":74,\"19\":29},\"t\":1637409499}\n NEW DATA ATRIBUTE: {\"dps\":{\"18\":76,\"19\":33},\"t\":1637409503}\n NEW DATA ATRIBUTE: {\"dps\":{\"19\":29},\"t\":1637409505}"
```

It’s weird when i look in the code i don’t see whats different then to other plugs. 18 19 and 20 are used for the power consumption just like neo and the others. but it says it’s unavailable

9 = always 0 ? even if turned of…
18 = current in mA
19 = Power (/10)
20 = voltage (/10

**Comment by rebtor** [comment]
Fixed
