### ISSUE TITLE
Hiya Problem with Fork

### ISSUE THREAD

**Issue by therealmcsparrow** [rebtor/nl.rebtor.tuya#6]
Hiya Rebtor

Sorry to bother you, but I created a fork from your git and when I do a Homey app run it gives this error:

2020-07-26 02:16:21 [log] [Tuyadriver] Tuyadriver is running...
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'tuydriver'
Require stack:
- /drivers/LSC_Smart_LED_Light_Strip/device.js
- /opt/homey-client/node_modules/homey-apps-sdk-v2/lib/Driver.js
- /opt/homey-client/node_modules/homey-apps-sdk-v2/index.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at Module.require (/opt/homey-client/node_modules/homey-apps-sdk-v2/index.js:14:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/drivers/LSC_Smart_LED_Light_Strip/device.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/drivers/LSC_Smart_LED_Light_Strip/device.js',
    '/opt/homey-client/node_modules/homey-apps-sdk-v2/lib/Driver.js',
    '/opt/homey-client/node_modules/homey-apps-sdk-v2/index.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap.js'
  ]
}

Any Ideas? the tuydriver exists in node_modules... or am I missing some things?

**Comment by rebtor** [comment]
Do you use the 5.0.0 / SDK 3 brach from homey because they changed around some stuff that makes it harder to use modules it seems. The latest code on this git should fix that.
